import type { Metadata } from "next";
import "../styles/globals.css";
import Faq from "./components/public/global/faq/Faq";
import Cta from "./components/public/global/Cta"

export const metadata: Metadata = {
  title: "Tecfy | Criação de Sites, Apps e Softwares",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className='antialiased'>
        <main >
          {children}
          <Faq></Faq>
          <Cta></Cta>
        </main>
      </body>
    </html>
  );
}
