import type { Metadata } from "next";
import "../styles/globals.css";
import Faq from "./components/public/global/faq/Faq";
import Cta from "./components/public/global/Cta"
import Footer from "./components/public/global/footer/Footer";
import Header from "./components/public/global/Header";
export const metadata: Metadata = {
  title: "Tecfy | Criação de Sites, Apps e Softwares",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className='antialiased'>
        <Header/>
        <main >
          {children}
          <Faq/>
          <Cta/>
        </main>
        <Footer/>
      </body>
    </html>
  );
}
